### PR TITLE
added bootstrap repo.

### PR DESCRIPTION
**Pull request by yliaog**
added bootstrap repo per https://github.com/kubernetes/kubernetes/pull/67356#issuecomment-414250981

### CODE REVIEW

**Comment by sttts** [comment]
Please ping here when the external repo is created, so I can merge and restart the bot.

**Comment by yliaog** [comment]
k8s.io/cluster-bootstrap is created. PTAL

**Comment by nikhita** [comment]
@sttts would be nice to merge this before we deploy again.

**Pull request merged**
