### PR TITLE
WIP: Run 'dep init' to create Gopkg.{toml,lock}

### PR DESCRIPTION
**Pull request by sttts**
Golang/dep does not support picking up these dependencies yet properly. But at least
dep will warn the user when he chooses incompatible dependencies (so did @munnerz report, but with `dep init --gopath` I did not even get warnings, but it picked up master which it shouldn't).

A test run was published to https://github.com/kubernetes-dep-experiment/client-go

**The goal is to vendor k8s.io/client-go, api, apimachinery and all other direct and transistive dependencies of client-go in the versions that are specified in  https://github.com/kubernetes-dep-experiment/client-go's Gopkg.{toml,lock} with only specifying the right branch or tag of client-go, i.e.**

```
[[constraint]]
  name = "k8s.io/client-go"
  version = "5.0.1"
```

For testing purposes one has to define the source for client-go, api and apimachinery to be in the kubernetes-dep-experiment org:

```
[[constraint]]
  name = "k8s.io/client-go"
  version = "5.0.1"
  source = "https://github.com/kubernetes-dep-experiment/client-go.git"

[[constraint]]
  name = "k8s.io/api"
  source = "https://github.com/kubernetes-dep-experiment/api.git"

[[constraint]]
  name = "k8s.io/apimachinery"
  source = "https://github.com/kubernetes-dep-experiment/apimachinery.git"
```

Compare https://github.com/sttts/kube-dep-test/blob/master/Gopkg.toml for a test project.

### CODE REVIEW

**Comment by sdboyer** [comment]
> so did @munnerz report, but with dep init --gopath I did not even get warnings, but it picked up master which it shouldn't

wait, this sounds like a dep bug? is the "report" you're referring to an issue that was filed? i don't recall seeing one, though i haven't been as diligent as usual this week.

**Comment by sttts** [comment]
> wait, this sounds like a dep bug? is the "report" you're referring to an issue that was filed? i don't recall seeing one, though i haven't been as diligent as usual this week.

I believe that was only a quick test with https://github.com/kubernetes-dep-experiment/client-go. Don't know that we have an issue for that, probably not.

@munnerz can you comment?

**Comment by sttts** [comment]
Possibly a simple route: https://github.com/kubernetes/publishing-bot/pull/55

**Pull request closed without merging**
