### PR TITLE
Bump default Go version to 1.12.9

### PR DESCRIPTION
**Pull request by tao12345666333**
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>

ref: https://github.com/kubernetes/kubernetes/pull/81489

### CODE REVIEW

**Comment by nikhita** [comment]
/hold cancel

/assign @sttts 
for approval

**Comment by tao12345666333** [comment]
> Looks like we should move this to the rules file

I think I missed this reply. :joy_cat:  What do you mean?

**Pull request merged**
