### PR TITLE
Drop unused replace directives

### LINKED ISSUE #214: Remove no-op replace directives from go.mod files
If the require and replace directive for a dependency match after running `go mod tidy`, drop the replace directive, since it is a no-op and confuses consumers

/assign

### PR DESCRIPTION
**Pull request by liggitt**
Tested locally, but would be good to run in nightly.

cc @sttts @nikhita 

Fixes #214

xref https://github.com/kubernetes/kubernetes/issues/85105

### CODE REVIEW

**Comment by nikhita** [comment]
While I agree that this is safer, can we directly `dropreplace` the dependencies?

This would also need to be updated in https://github.com/kubernetes/publishing-bot/blob/master/cmd/sync-tags/gomod.go.

**Comment by liggitt** [comment]
> While I agree that this is safer, can we directly `dropreplace` the dependencies?

I'm not sure what you're asking

**Comment by liggitt** [comment]
is this the relevant section:
https://github.com/kubernetes/publishing-bot/blob/master/cmd/sync-tags/gomod.go#L82-L88

I think it might be better to avoid adding the replace there in the first place if it doesn't already exist

**Comment by nikhita** [comment]
Would it be possible to skip the step in line 855 where we set the replace directive in the first place, instead of removing it after adding it? And then use `dropreplace` to replace the original replace directives like `k8s.io/api => ../api`?

https://github.com/kubernetes/publishing-bot/blob/ec388bdeb34233252eb18babc440d82a385c91b8/artifacts/scripts/util.sh#L854-L858

**Comment by nikhita** [comment]
> is this the relevant section:
https://github.com/kubernetes/publishing-bot/blob/master/cmd/sync-tags/gomod.go#L82-L88

yes

> I think it might be better to avoid adding the replace there in the first place if it doesn't already exist

I was wondering if something similar was also possible for util.sh as well.. :)

**Comment by liggitt** [comment]
I don't want to drop the replace until `go mod tidy` resolves/verifies it matches our naturally preferred version

**Comment by liggitt** [comment]
reopened in https://github.com/kubernetes/publishing-bot/pull/415 with updated version

**Pull request closed without merging**
