### PR TITLE
configs: get kubernetes rules from k/k repo

### PR DESCRIPTION
**Pull request by sttts**
Prequisite: https://github.com/kubernetes/kubernetes/pull/73023

### CODE REVIEW

**Comment by sttts** [comment]
/hold

until kubernetes/kubernetes#73023 merged.

**Comment by mfojtik** [comment]
LGTM

**Comment by nikhita** [comment]
/lgtm

The README needs an update too, but adding lgtm in case you want to get this merge and move it to another PR (happy to do it).

**Pull request merged**
