### PR TITLE
Skip all slow steps if there are no commits against the subdirectory

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by nikhita** [comment]
/remove-lifecycle stale

this looks ready to be merged

**Comment by sttts** [comment]
/hold

I question now that this PR works at all: even if there is no change in a subdirectory (e.g. staging/src/k8s.io/client-go), the dependencies might have changes (e.g. staging/src/k8s.io/apimachinery). And then we have to update at least the Godeps to avoid inconsistent Godep.json files in different sub-projects.

**Comment by nikhita** [comment]
@sttts Should this be closed?

**Comment by sttts** [comment]
With the recent speed improvement, I don't think we need this.

**Pull request closed without merging**
