### PR TITLE
repos.sh: add dynamic-resource-allocation

### PR DESCRIPTION
**Pull request by pohly**
This is needed for helper code for the dynamic resource allocation feature. The code will be added in https://github.com/kubernetes/kubernetes/pull/111023

The repo request is in https://github.com/kubernetes/org/issues/3821

### CODE REVIEW

**Comment by pohly** [comment]
/hold

The issue still needs SIG-Arch approval. It has SIG-Node approval.

**Comment by pohly** [comment]
/hold cancel

The repo has been approved by SIG Node and SIG Arch, we can proceed with setting it up.

**Comment by leonardpahlke** [comment]
> The repo has been approved by SIG Node and SIG Arch, we can proceed with setting it up.

Do you mind linking it? Thx

**Comment by pohly** [comment]
It's in the PR description and commit message: https://github.com/kubernetes/org/issues/3821

**Comment by pohly** [comment]
Or did you means some approval email? That I don't have.

**Comment by leonardpahlke** [comment]
> It's in the PR description and commit message: https://github.com/kubernetes/org/issues/3821
> 
> 

👍

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
