### PR TITLE
sync-tags: use go-git for fetching tags

### PR DESCRIPTION
**Pull request by nikhita**
If git is used directly while fetching tags, go-git doesn't recognize
annotated tags consistently. For example, there are instances where
it considers `refs/tags/upstream/*` as lightweight tags even though
`git for-each-ref refs/tags` clearly shows them as annotated tags.

This commits updates the fetch operation to use go-git directly to avoid
any inconsistencies while fetching and storing tags. Using go-git
removes this inconsistency and all annotated tags are recognized
properly.

Also, go-git now supports `*` in refspecs - https://github.com/src-d/go-git/blob/v4.9.1/config/refspec.go#L11.

---

We came across this error while deploying the bot recently. The bot doesn't recognize `refs/tags/upstream/*` as annotated, which makes sync-tags think that there are no new upstream tags and it skips syncing tags entirely. See [slack thread](https://kubernetes.slack.com/archives/C2C40FMNF/p1591792990209100?thread_ts=1591701817.194100&cid=C2C40FMNF) for more context.

/assign @dims @sttts

### CODE REVIEW

**Comment by nikhita** [comment]
/hold
for testing

**Comment by nikhita** [comment]
This is an example output for `git show-ref --tags` for apimachinery after creating new tags `v0.19.0-beta.1` and `kubernetes-1.19.0-beta.1` - https://gist.github.com/nikhita/d299aeda503edd72df58d6630967bea4

**Comment by sttts** [comment]
Sgtm.

**Comment by nikhita** [comment]
Nightly test run looks good: https://github.com/kubernetes-nightly/component-base/blob/v0.19.0-beta.2/go.mod :tada: 

/hold cancel

**Pull request merged**
