### PR TITLE
Re-enable kube 1.7

### PR DESCRIPTION
**Pull request by sttts**
TODO:
- [x] update all 1.7 staging branch: https://github.com/kubernetes/kubernetes/pull/57796
- [x] do a test run of the bot: https://github.com/sttts/client-go

### CODE REVIEW

**Comment by sttts** [comment]
@caesarxuchao I want to enable to the 1.7 sync again. Anything that speaks against it?

**Comment by caesarxuchao** [comment]
/lgtm

I manually downloaded the sttts/client-go release-4.0 and sttts/apimachinery, sttts/api into a clean directory, and verified that `godep restore`, `go build ./...` worked for client-go.

**Comment by sttts** [comment]
> I manually downloaded the sttts/client-go release-4.0 and sttts/apimachinery, sttts/api into a clean directory, and verified that godep restore, go build ./... worked for client-go.

Thanks! We actually have the smoke tests now which do the same thing on every run. Only the glide tests are still run manually by me locally.

**Comment by sttts** [comment]
Reployed the bot.

**Pull request merged**
