### PR TITLE
Add new staging repo: legacy-cloud-providers

### PR DESCRIPTION
**Pull request by nikhita**
Ref:

- Repo creation request: https://github.com/kubernetes/org/issues/719
- Repo with initial empty commit: https://github.com/kubernetes/legacy-cloud-providers
- PR against test-infra for branch protection: https://github.com/kubernetes/test-infra/pull/12220
- PR for to add repo to staging against k/k: https://github.com/kubernetes/kubernetes/pull/75910
- PR for updating publishing-bot rules against k/k: https://github.com/kubernetes/kubernetes/pull/75910/commits/8e508598982bbd9b392eaf7b0aaaed6f833a9e94#diff-91f67bda331c4de19a3b70c86f69a080
- @kubernetes/stage-bots team has admin access to the repo :heavy_check_mark: 

/hold
Needs to be added to staging, rules need to be updated and branch protection PR needs to be merged.

/cc @dims @sttts @andrewsykim 
/assign @sttts

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm

(don't think my approve will help!)

**Comment by nikhita** [comment]
/hold cancel
branch protection PR has merged. Rules need to be updated _after_ this PR gets merged because we need to be able to clone the repo first.

Merging this PR before adding the rules is ok because this will just clone and push the latest changes (there aren't any new changes though).

**Pull request merged**
