### PR TITLE
Bump default go version to 1.12

### PR DESCRIPTION
**Pull request by nikhita**
Ref: https://github.com/kubernetes/kubernetes/pull/74632

/cc @dims @sttts

### CODE REVIEW

**Comment by sttts** [comment]
Have we hardcoded the version everywhere else, so that this is has no consequences?

**Comment by nikhita** [comment]
> Have we hardcoded the version everywhere else

No, we don't hard code the default go version anywhere else.

The only other place we hardcore the go version is in the rules. But the rules don't hard code the go version for the master branch - only the release branches. The `defaultGoVersion` is used for the master branch.

And the go version for all 1.14 branches has been updated to 1.12 in https://github.com/kubernetes/kubernetes/pull/74664. :+1: 

https://github.com/kubernetes/kubernetes/blob/master/staging/publishing/rules.yaml

**Pull request merged**
