### PR TITLE
Add 1.12 branches to new staging repos

### PR DESCRIPTION
**Pull request by sttts**
Based on https://github.com/kubernetes/publishing-bot/pull/97

### CODE REVIEW

**Comment by sttts** [comment]
Smoke test is running.

/hold

**Comment by sttts** [comment]
Kind of accidently merged due to https://github.com/kubernetes/publishing-bot/pull/101. No big issue. Bot is running. Am optimistic it succeeds.

**Comment by dims** [comment]
thanks @sttts how long does it usually take to finish? (given that it's late for you there)

**Comment by sttts** [comment]
Repos have been published. 🎉

**Pull request merged**
