### PR TITLE
Add apiextensions as a dependency to csi-api

### PR DESCRIPTION
**Pull request by nikhita**
publishing-bot is currently broken: https://github.com/kubernetes/kubernetes/issues/56876

https://github.com/kubernetes/kubernetes/pull/68579 added apiextensions-apiserver as a dependency to csi-api but it is not listed as a dependency here, which breaks publishing-bot while reconstructing godeps.json.

This is the relevant part of the error log:

```sh
++ git commit-tree -p 2966180a4e54fab57c98153a33cf018cc4017ba3 -p HEAD -m 'Merge pull request #68579 from verult/adc-crd-access

    	Updating CSI e2e test to create CSI CRDs

...

+ update_full_godeps apimachinery:master,api:master,client-go:master k8s.io true Kubernetes-commit
    	+ local deps=apimachinery:master,api:master,client-go:master
    	+ local base_package=k8s.io
    	+ local is_library=true
    	+ local commit_msg_tag=Kubernetes-commit
    	+ ensure-clean-working-dir
    	+ git diff HEAD --exit-code
    	+ for d in '$../*'
    	+ '[' '!' -d '$../*' ']'
    	+ continue
    	+ '[' '!' -f Godeps/Godeps.json ']'
    	+ echo 'Removing k8s.io/* dependencies from Godeps.json'
    	+ local dep=
    	+ local branch=
    	+ local depbranch=
    	++ basename /go-workspace/src/k8s.io/csi-api
    	+ for depbranch in '${deps//,/ }' '$(basename "${PWD}")'
    	+ IFS=:
    	+ read dep branch
    	+ jq '.Deps |= map(select(.ImportPath | (startswith("k8s.io/apimachinery/") or . == "k8s.io/apimachinery") | not))' Godeps/Godeps.json
    	+ indent-godeps
    	+ unexpand --first-only --tabs=2
    	+ mv Godeps/Godeps.json.clean Godeps/Godeps.json
    	+ for depbranch in '${deps//,/ }' '$(basename "${PWD}")'
    	+ IFS=:
    	+ read dep branch
    	+ jq '.Deps |= map(select(.ImportPath | (startswith("k8s.io/api/") or . == "k8s.io/api") | not))' Godeps/Godeps.json
    	+ indent-godeps
    	+ unexpand --first-only --tabs=2
    	+ mv Godeps/Godeps.json.clean Godeps/Godeps.json
    	+ for depbranch in '${deps//,/ }' '$(basename "${PWD}")'
    	+ IFS=:
    	+ read dep branch
    	+ jq '.Deps |= map(select(.ImportPath | (startswith("k8s.io/client-go/") or . == "k8s.io/client-go") | not))' Godeps/Godeps.json
    	+ indent-godeps
    	+ unexpand --first-only --tabs=2
    	+ mv Godeps/Godeps.json.clean Godeps/Godeps.json
    	+ for depbranch in '${deps//,/ }' '$(basename "${PWD}")'
    	+ IFS=:
    	+ read dep branch
    	+ jq '.Deps |= map(select(.ImportPath | (startswith("k8s.io/csi-api/") or . == "k8s.io/csi-api") | not))' Godeps/Godeps.json
    	+ indent-godeps
    	+ unexpand --first-only --tabs=2
    	+ mv Godeps/Godeps.json.clean Godeps/Godeps.json
    	+ echo 'Running godep restore.'
    	+ godep restore
    	# cd /go-workspace/src/k8s.io/apiextensions-apiserver; git checkout xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    	error: pathspec 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' did not match any file(s) known to git.
    	godep: error restoring dep (k8s.io/apiextensions-apiserver/pkg/apis/apiextensions): exit status 1
    	# cd /go-workspace/src/k8s.io/apiextensions-apiserver; git checkout xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    	error: pathspec 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' did not match any file(s) known to git.
    	godep: error restoring dep (k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1): exit status 1
    	# cd /go-workspace/src/k8s.io/apiextensions-apiserver; git checkout xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    	error: pathspec 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' did not match any file(s) known to git.
    	godep: error restoring dep (k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme): exit status 1
    	godep: Error restoring some deps. Aborting check.

[21 Sep 18 11:02 UTC]: exit status 1```
```

### CODE REVIEW

**Comment by nikhita** [comment]
/assign @sttts @caesarxuchao 

@caesarxuchao if this lgty, can you lgtm+approve since @sttts is OOO?

**Comment by nikhita** [comment]
cc @verult @saad-ali

**Comment by apelisse** [comment]
@nikhita Do you know how we can prevent that from happening again? I'm assuming we don't want to create a new PR every time a new dependency is added.

**Comment by nikhita** [comment]
> @nikhita Do you know how we can prevent that from happening again? I'm assuming we don't want to create a new PR every time a new dependency is added.

I'm not entirely sure how to make this automated but a quick fix I can think of right now is adding a comment about updating the publishing bot in [`hack/import-restrictions.yaml`](https://github.com/kubernetes/kubernetes/blob/master/hack/import-restrictions.yaml).

This list in the publishing bot here needs to be updated only if a new dependency to a staging repo is added (which should be pretty rare) and should be caught by the import restrictions script.

The import restrictions file currently does not contain csi-api at all. I have created a PR to add it: https://github.com/kubernetes/kubernetes/pull/68942.

**Comment by apelisse** [comment]
Thanks for following up!

**Comment by sttts** [comment]
Redployed the bot.

**Pull request merged**
