### PR TITLE
Update OWNERS to current reviewers

### PR DESCRIPTION
**Pull request by nikhita**
This PR updates OWNERS to current reviewers.

/assign @dims @sttts 

@apelisse @marun @munnerz Let me know if you'd like to stay and I can add you back. :)

I'll keep this open till EOW so that everyone can chime in.

### CODE REVIEW

**Comment by apelisse** [comment]
I'm happy with this change, I don't have a lot of interest or time to look at these PR :-)

**Comment by dims** [comment]
Thanks @nikhita @sttts

**Comment by nikhita** [comment]
To be clear, I'm making this change because I intend to link the OWNERS file as people who should be reached out to incase of publishing bot failures/questions.

(going to add some docs as part of https://github.com/kubernetes/kubernetes/pull/74664#issuecomment-467914046 and some github-management stuff)

**Comment by nikhita** [comment]
Cancelling the hold since lazy consensus period is over.

/hold cancel

**Pull request merged**
