### PR TITLE
update to go 1.20 and bump golang.org/x/net

### PR DESCRIPTION
**Pull request by cpanato**
- update to go 1.20 and bump golang.org/x/net

go 1.17 is deprecated and we should move this to the latest available

### CODE REVIEW

**Comment by cpanato** [comment]
maybe require an update in the prow jobs

**Comment by dims** [comment]
@cpanato the failures look legit!

**Comment by cpanato** [comment]
> @cpanato the failures look legit!

Yes, did a pr to update the jobs. Afyer that any other issue i will fix

**Pull request merged**
